// <auto-generated />
using GSO_Hotelreservierung.Daten;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GSO_Hotelreservierung.Migrations
{
    [DbContext(typeof(HotelreservierungContext))]
    [Migration("20240327234904_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("GSO_Hotelreservierung.Model.Kunde", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefonnummer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kunden");
                });

            modelBuilder.Entity("GSO_Hotelreservierung.Model.Reservierung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kunde")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Zimmer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("chechkInDatum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("checkOutDatum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Reservierungen");
                });

            modelBuilder.Entity("GSO_Hotelreservierung.Model.ZimmerKategorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kategorie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preis")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ZimmerKategorien");
                });
#pragma warning restore 612, 618
        }
    }
}
